Added tellor360 contractset
tellor-io/telliot-core pull request #321
Opened 2022-09-29 12:52 UTC by akremstudy

For oracle and autopay, added:
- contract addresses to contract_directory
- abi
- and created the 360 contractset (oracle, autopay, and token(existing).

2022-09-29 13:58 UTC, akremstudy commented
@oraclown can you please take a look at the tox style run, I haven't seen that error before. Did something change in the way the test is ran?

2022-10-03 13:43 UTC, oraclown requested changes
Thanks for this @akremstudy ! Think any unit tests should be added to make sure everything's working fine now and when changes are made in the future?

2022-10-03 13:43 UTC, oraclown commented on src/telliot_core/apps/core.py
> +        """Get or create TellorX contracts"""
It says tellorx

2022-10-03 13:43 UTC, oraclown commented on src/telliot_core/tellor/tellor360/autopay.py
> +        contract_info = contract_directory.find(chain_id=chain_id, name="tellor360-autopay")[0]
Will throw an index error if there's no 260 contracts for the desired chain

2022-10-04 01:17 UTC, akremstudy commented
> Thanks for this @akremstudy ! Think any unit tests should be added to make sure everything's working fine now and when changes are made in the future?

I don't think deploying to brownie and testing is necessary since no functions are added to the files and contract read or write are tested already but if you think it is let me know.

2022-10-04 13:56 UTC, merged