Add optimisim network
tellor-io/telliot-core pull request #357
Opened 2023-02-16 15:56 UTC by akremstudy

added-OP (no gas source)

2023-02-16 19:29 UTC, akremstudy commented
@oraclown, is this cool for now?

2023-02-16 21:19 UTC, oraclown requested changes
thanks @akremstudy ! I will take a look at the failing code fmt stuff tomorrow. I think we should refactor this a little b4 merging. If @spuddyminer needs this to report ASAP, then switch to this branch and update the telliot-feeds dep to be this branch.. in a separate env.

2023-02-16 21:19 UTC, oraclown commented on src/telliot_core/gas/legacy_gas.py
> +    if isinstance(speed, tuple):
I think we can refactor this logic of retrieving the price like in #358 , as an example

2023-02-17 17:08 UTC, spuddyminer commented
tested for reporting on optimism, and gas estimation works great!

2023-02-17 17:32 UTC, oraclown approved these changes
Nice, thanks @akremstudy !

2023-02-17 17:35 UTC, merged